// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqefbgvpzvggvvmizidb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxZWZiZ3ZwenZnZ3Z2bWl6aWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjkzNzAsImV4cCI6MjA2MzkwNTM3MH0.mf_eevt1xnwAacZTvFQV_QIq34eMGpV1J9-QS10x7Uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);